/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRemixRouteImport } from './routes/_authenticated.remix'
import { Route as AuthenticatedMeusConteudosRouteImport } from './routes/_authenticated.meus-conteudos'
import { Route as AuthenticatedMeuNegocioRouteImport } from './routes/_authenticated.meu-negocio'
import { Route as AuthenticatedGeradorRouteImport } from './routes/_authenticated.gerador'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated.configuracoes'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRemixRoute = AuthenticatedRemixRouteImport.update({
  id: '/remix',
  path: '/remix',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMeusConteudosRoute =
  AuthenticatedMeusConteudosRouteImport.update({
    id: '/meus-conteudos',
    path: '/meus-conteudos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMeuNegocioRoute = AuthenticatedMeuNegocioRouteImport.update({
  id: '/meu-negocio',
  path: '/meu-negocio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGeradorRoute = AuthenticatedGeradorRouteImport.update({
  id: '/gerador',
  path: '/gerador',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/gerador': typeof AuthenticatedGeradorRoute
  '/meu-negocio': typeof AuthenticatedMeuNegocioRoute
  '/meus-conteudos': typeof AuthenticatedMeusConteudosRoute
  '/remix': typeof AuthenticatedRemixRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/gerador': typeof AuthenticatedGeradorRoute
  '/meu-negocio': typeof AuthenticatedMeuNegocioRoute
  '/meus-conteudos': typeof AuthenticatedMeusConteudosRoute
  '/remix': typeof AuthenticatedRemixRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/gerador': typeof AuthenticatedGeradorRoute
  '/_authenticated/meu-negocio': typeof AuthenticatedMeuNegocioRoute
  '/_authenticated/meus-conteudos': typeof AuthenticatedMeusConteudosRoute
  '/_authenticated/remix': typeof AuthenticatedRemixRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/configuracoes'
    | '/gerador'
    | '/meu-negocio'
    | '/meus-conteudos'
    | '/remix'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/configuracoes'
    | '/gerador'
    | '/meu-negocio'
    | '/meus-conteudos'
    | '/remix'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/configuracoes'
    | '/_authenticated/gerador'
    | '/_authenticated/meu-negocio'
    | '/_authenticated/meus-conteudos'
    | '/_authenticated/remix'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/remix': {
      id: '/_authenticated/remix'
      path: '/remix'
      fullPath: '/remix'
      preLoaderRoute: typeof AuthenticatedRemixRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/meus-conteudos': {
      id: '/_authenticated/meus-conteudos'
      path: '/meus-conteudos'
      fullPath: '/meus-conteudos'
      preLoaderRoute: typeof AuthenticatedMeusConteudosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/meu-negocio': {
      id: '/_authenticated/meu-negocio'
      path: '/meu-negocio'
      fullPath: '/meu-negocio'
      preLoaderRoute: typeof AuthenticatedMeuNegocioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gerador': {
      id: '/_authenticated/gerador'
      path: '/gerador'
      fullPath: '/gerador'
      preLoaderRoute: typeof AuthenticatedGeradorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedGeradorRoute: typeof AuthenticatedGeradorRoute
  AuthenticatedMeuNegocioRoute: typeof AuthenticatedMeuNegocioRoute
  AuthenticatedMeusConteudosRoute: typeof AuthenticatedMeusConteudosRoute
  AuthenticatedRemixRoute: typeof AuthenticatedRemixRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedGeradorRoute: AuthenticatedGeradorRoute,
  AuthenticatedMeuNegocioRoute: AuthenticatedMeuNegocioRoute,
  AuthenticatedMeusConteudosRoute: AuthenticatedMeusConteudosRoute,
  AuthenticatedRemixRoute: AuthenticatedRemixRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
